videos = { '1':     ['https://www.youtube.com/watch?v=IpjNO5mr-W8'],
             '2':     ['https://www.youtube.com/watch?v=Z9LT10EJnyU&t=5s'],
             '3' :    ['https://www.youtube.com/watch?v=D_as7uDaNXg&t=6s'],
             '4':     ['https://www.youtube.com/watch?v=2bxkqBzrIPM&t=23s'],
             '5':     ['https://www.youtube.com/watch?v=odlAUid4DNw&t=3s'],
             '6':     ['https://www.youtube.com/watch?v=aeZxJPlWMrE&t=5s'],
             '7':     ['https://www.youtube.com/watch?v=9BN68C1S5gY&t=7s'],
             '8':     ['https://www.youtube.com/watch?v=P7xbnZ9NyRE'],
             '9':     ['https://www.youtube.com/watch?v=hsy8otNXLjM'],
             '10':    ['https://www.youtube.com/watch?v=hsy8otNXLjM&t=2s'],
             '11':    ['https://youtu.be/d7-xkzQVLII'],
             '12':    ['https://youtu.be/vyaqmNFyOmA'],
             '13':    ['https://youtu.be/tV5khFzsgd8'],
             '14':    ['https://youtu.be/Egi6rpaztlY', 'https://youtu.be/jiWQT30R_E8'],
             '15':    ['https://youtu.be/Bf-GAECMbTk'],
             '16':    ['https://www.youtube.com/watch?v=X3zRwgDEPAI'],
             '17':    ['https://www.youtube.com/watch?v=E22_Ooh5Wgo'],
             '18':    ['https://www.youtube.com/watch?v=Ydbi9YDJTfU'],
             '19-21': ['https://www.youtube.com/watch?v=4p_OgVueVwQ'],
             '22' :   ['https://www.youtube.com/watch?v=P4YBg-hwXPo'],
             '23':    ['https://www.youtube.com/watch?v=e40irD10seU'],
             '24':   ['https://www.youtube.com/watch?v=7zCUCFlCFBY'],
             '25' :   ['https://www.youtube.com/watch?v=6DuTe5ixS4s'],
             '26' :   ['https://www.youtube.com/watch?v=9VEyDZ4FhSc'],
             '27' :   ['https://www.youtube.com/watch?v=0D89y1c1Nw0'],
            }